In [1]:
from google.colab import files
uploaded = files.upload()

Saving glass.csv to glass.csv

In [2]:
import pandas as pd
df = pd.read_csv('glass.csv')
df

,Id,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type of glass
0,1,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,1
1,2,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,1
2,3,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,1
3,4,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,1
4,5,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...
209,210,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,7
210,211,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,7
211,212,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,7
212,213,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,7
213,214,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,7

In [5]:
df.isnull().sum()

Id               0
RI               0
Na               0
Mg               0
Al               0
Si               0
K                0
Ca               0
Ba               0
Fe               0
Type of glass    0
dtype: int64

In [6]:
X = df.drop('Type of glass',axis=1)
Y = df['Type of glass']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [8]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [9]:
df['Type of glass'].value_counts()

Type of glass
2    76
1    70
7    29
3    17
5    13
6     9
Name: count, dtype: int64

In [10]:
df['Type of glass'].value_counts(normalize=True)*100

Type of glass
2    35.514019
1    32.710280
7    13.551402
3     7.943925
5     6.074766
6     4.205607
Name: proportion, dtype: float64

In [11]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, Y)

In [12]:
print(pd.Series(y_resampled).value_counts())

Type of glass
1    76
2    76
3    76
5    76
6    76
7    76
Name: count, dtype: int64

In [13]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(multi_class='multinomial')
LR.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(multi_class='multinomial')

In [25]:
LR.score(X_test,Y_test)

1.0

In [28]:
train_score = LR.score(X_train, Y_train)
test_score  = LR.score(X_test, Y_test)
print(f"Train : {train_score:.4f}")
print(f"Test  : {test_score:.4f}")

Train : 0.9942
Test  : 1.0000

In [14]:
y_predict = LR.predict(X_test)
y_predict

array([1, 7, 1, 7, 2, 2, 1, 2, 2, 2, 6, 5, 2, 2, 6, 5, 7, 1, 1, 6, 2, 7,
       7, 7, 3, 2, 1, 1, 5, 1, 1, 2, 3, 2, 1, 7, 5, 3, 2, 2, 2, 7, 1])

In [24]:
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score,confusion_matrix

print("Accuracy  :", accuracy_score(Y_test, y_predict))
print("Precision :", precision_score(Y_test, y_predict, average='macro'))
print("Recall    :", recall_score(Y_test, y_predict,    average='macro'))
print("F1 Score  :", f1_score(Y_test, y_predict,        average='macro'))
print("Confusion matrix :",confusion_matrix(Y_test,y_predict))

Accuracy  : 1.0
Precision : 1.0
Recall    : 1.0
F1 Score  : 1.0
Confusion matrix : [[11  0  0  0  0  0]
 [ 0 14  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  8]]