In [1]:
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart.csv

In [2]:
import pandas as pd
df = pd.read_csv('heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [21]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [3]:
X = df.drop('target',axis=1)
Y = df['target']

In [4]:
df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [20]:
df['target'].value_counts(normalize=True)*100

target
1    51.317073
0    48.682927
Name: proportion, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [23]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, Y_resampled = smote.fit_resample(X, Y)

In [24]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [28]:
print("Training set shape:", X_train_scaled.shape)
print("Testing set shape:", X_test_scaled.shape)

Training set shape: (820, 13)
Testing set shape: (205, 13)

In [25]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(max_iter=1000)
LR.fit(X_train,Y_train)

LogisticRegression(max_iter=1000)

In [26]:
y_predict = LR.predict(X_test)
y_predict

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0])

In [29]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score
print("Accuracy : ",accuracy_score(Y_test,y_predict))
print("Precision : ", precision_score(Y_test,y_predict))
print("Recall : ", recall_score(Y_test,y_predict))
print("F1 Score : ",f1_score(Y_test,y_predict))

Accuracy :  0.7951219512195122
Precision :  0.7563025210084033
Recall :  0.8737864077669902
F1 Score :  0.8108108108108109

In [19]:

# Create new patient data as DataFrame
new_patient = pd.DataFrame({
    'age'      : [52],
    'sex'      : [1],
    'cp'       : [0],
    'trestbps' : [125],
    'chol'     : [212],
    'fbs'      : [0],
    'restecg'  : [1],
    'thalach'  : [168],
    'exang'    : [0],
    'oldpeak'  : [1.0],
    'slope'    : [2],
    'ca'       : [2],
    'thal'     : [3]
})

# Scale using SAME scaler used in training
new_patient_scaled = scaler.transform(new_patient)
prediction = LR.predict(new_patient_scaled)

# Result
if prediction[0] == 1:
    print("Result: Heart Disease Detected ❤️")
elif prediction[0] == 0:
    print("Result: No Heart Disease ✅")

Result: Heart Disease Detected ❤️

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(