In [17]:
import pandas as pd
from sklearn.datasets import load_wine
diabets = load_wine()
X = diabets.data
Y = diabets.target

In [18]:
df = pd.DataFrame(X,columns=diabets.feature_names)
df['target'] = Y

In [19]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [20]:
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [22]:
print(diabets.target_names)

['class_0' 'class_1' 'class_2']

In [23]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size = 0.2 , random_state=42)

In [24]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
df['target'].value_counts()

target
1    71
0    59
2    48
Name: count, dtype: int64

In [27]:
df['target'].value_counts(normalize=True) * 100

target
1    39.887640
0    33.146067
2    26.966292
Name: proportion, dtype: float64

In [28]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, Y)

In [29]:
print(pd.Series(y_resampled).value_counts())

0    71
1    71
2    71
Name: count, dtype: int64

In [31]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(multi_class='multinomial')
LR.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(multi_class='multinomial')

In [33]:
y_predict = LR.predict(X_test)
y_predict

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0])

In [36]:
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score

print("Accuracy  :", accuracy_score(Y_test, y_predict))
print("Precision :", precision_score(Y_test, y_predict, average='macro'))
print("Recall    :", recall_score(Y_test, y_predict,    average='macro'))
print("F1 Score  :", f1_score(Y_test, y_predict,        average='macro'))

Accuracy  : 0.9722222222222222
Precision : 0.9777777777777779
Recall    : 0.9761904761904763
F1 Score  : 0.9761600681140911

In [44]:
train_score = LR.score(X_train, Y_train)
test_score  = LR.score(X_test, Y_test)
print(f"Train : {train_score:.4f}")
print(f"Test  : {test_score:.4f}")

Train : 0.9648
Test  : 0.9722

In [38]:
print(diabets.data[0])

[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]

In [39]:
print(diabets.target_names)

['class_0' 'class_1' 'class_2']

In [42]:
new_data = [[1.423, 1.710, 2.430, 1.560, 1.270, 2.800, 3.060,
 2.800,2.290,5.640,1.040,3.920,1.065]]
new_data_scaled = scaler.transform(new_data)
prediction = LR.predict(new_data_scaled)
if prediction[0] == 0:
   print("Class_0")
elif prediction[0] == 1:
     print("Class_1")
elif prediction[0] == 2:
     print("Class_2")

Class_0